In [1]:
import pandas as pd
import sys
print(sys.version)
print("pandas version" , pd.__version__)

3.10.19 (main, Oct 21 2025, 16:43:05) [GCC 11.2.0]
pandas version 2.3.3

In [29]:
##import dataset
DATASET_PATH='dataset/'
df=pd.read_csv(DATASET_PATH+"dataset_with_prompt.csv")
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              150 non-null    int64
 1   Title           150 non-null    object
 2   Poet            150 non-null    object
 3   text            150 non-null    object
 4   ctext           150 non-null    object
 5   Poem Link       150 non-null    object
 6   our_summary     150 non-null    object
 7   prompt_summary  150 non-null    object
 8   video_path      12 non-null     object
dtypes: int64(1), object(8)
memory usage: 10.7+ KB

(150, 9)

In [4]:
df.head()

,id,Title,Poet,text,ctext,Poem Link,our_summary
0,0,"Dear John, Dear Coltrane by Michael S. Harper",Michael S. Harper,"'Dear John, Dear Coltrane' by Michael S. Harpe...","a love supreme, a love supreme\na love supreme...",https://www.poetryfoundation.org/poems/42827/d...,"The poem explores themes of love, loss, pain, ..."
1,1,Parrot by Stevie Smith,Stevie Smith,‘Parrot‘ depicts the declining health of a won...,The old sick green parrot\nHigh in a dingy cag...,https://revise.wales/pastPapers/A-level/Englis...,"This old parrot, sick and full of rage, longs ..."
2,2,Dust of Snow by Robert Frost,Robert Frost,"The simplicity, in the end, is the key element...",The way a crow\nShook down on me\nThe dust of ...,https://www.poetryfoundation.org/poems/44262/d...,The sight of a crow shaking snow from a tree t...
3,3,Suburban Sonnet by Gwen Harwood,Gwen Harwood,'Suburban Sonnet' by Gwen Harwood is a poem ab...,"She practises a fugue, though it can matter\nt...",https://genius.com/Gwen-harwood-suburban-sonne...,"A mother practices music, but her children int..."
4,4,Unending Love by Rabindranath Tagore,Rabindranath Tagore,'Unending Love' by Rabindranath Tagore is a he...,"I seem to have loved you in numberless forms, ...",https://allpoetry.com/Unending-Love,The speaker expresses their eternal love for s...

In [7]:
ndf=df[['text','ctext','our_summary']]
ndf.head()

,text,ctext,our_summary
0,"'Dear John, Dear Coltrane' by Michael S. Harpe...","a love supreme, a love supreme\na love supreme...","The poem explores themes of love, loss, pain, ..."
1,‘Parrot‘ depicts the declining health of a won...,The old sick green parrot\nHigh in a dingy cag...,"This old parrot, sick and full of rage, longs ..."
2,"The simplicity, in the end, is the key element...",The way a crow\nShook down on me\nThe dust of ...,The sight of a crow shaking snow from a tree t...
3,'Suburban Sonnet' by Gwen Harwood is a poem ab...,"She practises a fugue, though it can matter\nt...","A mother practices music, but her children int..."
4,'Unending Love' by Rabindranath Tagore is a he...,"I seem to have loved you in numberless forms, ...",The speaker expresses their eternal love for s...

In [26]:

row_num=9
for c in ['Title','ctext','text','our_summary']:
    print(c)
    print(df.loc[row_num,c])
    print("-"*90)

Title
Babies by Alice Fulton
------------------------------------------------------------------------------------------
ctext
born gorgeous with nerves, with brains
the pink of silver polish or
jellyfish wafting ornately
through the body below.
An invertebrate cooing
on the mother
tongue shushes and lulls them into thinking
all is well. As they grow they learn

salvage: tear-out
guides to happiness say apologies can outshine
lies, guilt be lickspittled from their lives, bad
glycerined to good. Like a child’s first school pencils
in their formal brilliance
and sharp new smells, they lie

as lovers. Maybe one cries
the wrong name and the night skinning
them pleasantly alive
leaps away in shards.
Then it’s time for restitution:
a tin of homebaked,
holding gingham safety, fetal
as the light through mason jars of beets and brine,
or jewelry, clasping and unclasping
aisles of fluorescence from great department stores,
a distracting plenitude, and tempting.

Still, the beloved may stay bitter as an ear
the tongue pressed
into, unwanted.
And the word end: spiney, finally-formed,
indents them and is
understood. They learn

the hard way as hurts
accrue, and the brain is cratered as a rock
by rain that fell ages past
on unprotected mud. An insult keeps
despite apologies. When it vaporizes at last,
its space fills with grains that harden
to a fossil shaped exactly
like the insult.
They grow up when they know that

sometimes
only a gesture responsive as a heart-
shaped parachute above a jump
a life depends on
to be perfect
the first time will ever do
------------------------------------------------------------------------------------------
text
'Babies' by Alice Fulton is a powerful poem filled with images that describe what it's like to age from childhood into adulthood. In the first lines of this poem, the speaker describes what a child is like when they're born. They are lulled by their mother's soothing voice into thinking that everything is going to be all right. Life feels simple when one is young. But, as a child ages, they learn that not all lies or mistakes can be erased. The poet uses an example of a scorned lover, called by the wrong name while in bed, whose affections cannot be regained. One simple mistake can ruin someone's chances at happiness. The poem concludes with a very effective image comparing life, or at least some parts of it, to a parachuter jumping out of a plane. One has a single chance to get things right.
------------------------------------------------------------------------------------------
our_summary
The poem explores the journey of growth and learning through experiences and relationships. It touches on the idea that appearances can be deceiving, apologizing may not always erase guilt, and sometimes hurtful words leave a lasting impact. The speaker emphasizes the importance of genuine gestures and the realization that perfection is not always attainable. Ultimately, growth comes from understanding and accepting life's imperfections.
------------------------------------------------------------------------------------------